auction/apps/auction_web/lib/auction_web/router.ex
defmodule AuctionWeb.Router do
  use AuctionWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {AuctionWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug AuctionWeb.Authenticator
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AuctionWeb do
    pipe_through :browser
    
    get "/", PageController, :index
    resources "/items", ItemController do
      resources "/bids", BidController, only: [:create]
    end
    resources "/users", UserController, only: [:show, :new, :create]
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", AuctionWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: AuctionWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

auction/apps/auction_web/lib/auction_web/controllers/bid_controller.ex
defmodule AuctionWeb.BidController do
  use AuctionWeb, :controller
  plug :require_logged_in_user

  def create(conn, %{"bid" => %{"amount" => amount}, "item_id" => item_id}) do
    user_id = conn.assigns.current_user.id
    case Auction.insert_bid(%{"amount" => amount, "item_id" => item_id, "user_id" => user_id}) do
      {:ok, bid} ->
        redirect(conn, to: Routes.item_path(conn, :show, bid.item_id))
      {:error, bid} ->
        item = Auction.get_item_with_bids(item_id)
        render(conn, AuctionWeb.ItemView, "show.html", item: item, bid: bid)
    end
  end

  defp require_logged_in_user(%{assigns: %{current_user: nil}} = conn, _opts) do
    conn
    |> put_flash(:error, "Nice try, friend. You must be logged in to bid.")
    |> redirect(to: Routes.item_path(conn, :index))
    |> halt()
  end

  defp require_logged_in_user(conn, _opts), do: conn
end

auction/apps/auction_web/lib/auction_web/controllers/item_controller.ex
defmodule AuctionWeb.ItemController do
  use AuctionWeb, :controller
  plug :require_logged_in_user

  def index(conn, _params) do
    items = Auction.list_items()
    render(conn, "index.html", items: items)
  end

  def show(conn, %{"id" => id}) do
    item = Auction.get_item_with_bids(id)
    conn = assign(conn, :current_item, item)
    bid = Auction.new_bid()
    render(conn, "show.html", item: item, bid: bid)
  end

  def new(conn, _params) do
    item = Auction.new_item()
    render(conn, "new.html", item: item)
  end

  def create(conn, %{"item" => params}) do
    params = Map.put(params, "user_id", conn.assigns.current_user.id)
    case Auction.insert_item(params) do
      {:ok, item} -> redirect(conn, to: Routes.item_path(conn, :show, item))
      {:error, item} -> render(conn, "new.html", item: item)
    end
  end

  def edit(conn, %{"id" => id}) do
    item = Auction.edit_item(id)
    render(conn, "edit.html", item: item)
  end

  @spec update(Plug.Conn.t(), map) :: Plug.Conn.t()
  def update(conn, %{"id" => id, "item" => params}) do
    item = Auction.get_item(id)
    if item.user_id != conn.assigns.current_user.id do
      conn
      |> put_flash(:error, "Nice try, friend. You must be the owner of this item to edit it.")
      |> redirect(to: Routes.item_path(conn, :show, item))
    else
      case Auction.update_item(item, params) do
        {:ok, item} -> redirect(conn, to: Routes.item_path(conn, :show, item))
        {:error, item} -> render(conn, "edit.html", item: item)
      end
    end
  end

  defp require_logged_in_user(%{
    assigns: %{current_user: nil},
    private: %{phoenix_action: action},
  } = conn, _opts) when action not in [:index, :show] do
    conn
    |> put_flash(:error, "Nice try, friend. You must be logged in to manage item.")
    |> redirect(to: Routes.item_path(conn, :index))
    |> halt()
  end
  defp require_logged_in_user(conn, _opts), do: conn
end

auction/apps/auction_web/lib/auction_web/controllers/page_controller.ex
defmodule AuctionWeb.PageController do
  use AuctionWeb, :controller

  def index(conn, _params) do
    items = Auction.list_items()
    render(conn, "index.html", items: items)
  end
end

auction/apps/auction_web/lib/auction_web/controllers/session_controller.ex
defmodule AuctionWeb.SessionController do
  use AuctionWeb, :controller

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"user" => %{"username" => username, "password" => password}}) do
    case Auction.get_user_by_username_and_password(username, password) do
      %Auction.User{} = user ->
        conn
        |> put_session(:user_id, user.id)
        |> put_flash(:info, "Successfully logged in")
        |> redirect(to: Routes.user_path(conn, :show, user))
      _ ->
        conn
        |> put_flash(:error, "Invalid username or password")
        |> render("new.html")
    end
  end

  def delete(conn, _params) do
    conn
    |> clear_session()
    |> configure_session(drop: true)
    |> redirect(to: Routes.item_path(conn, :index))
  end
end

auction/apps/auction_web/lib/auction_web/controllers/user_controller.ex
defmodule AuctionWeb.UserController do
  use AuctionWeb, :controller
  plug :prevent_unauthorized_access when action in [:show]

  def show(conn, %{"id" => id}) do
    user = Auction.get_user(id)
    bids = Auction.get_bids_for_user(user)
    render(conn, "show.html", user: user, bids: bids)
  end

  def new(conn, _params) do
    user = Auction.new_user()
    render(conn, "new.html", user: user)
  end

  def create(conn, %{"user" => params}) do
    case Auction.insert_user(params) do
      {:ok, user} -> redirect(conn, to: Routes.user_path(conn, :show, user))
      {:error, user} -> render(conn, "new.html", user: user)
    end
  end

  defp prevent_unauthorized_access(conn, _opts) do
    current_user = conn.assigns[:current_user]
    requested_user_id =
      conn.params
      |> Map.get("id")
      |> String.to_integer()

    if current_user == nil || current_user.id != requested_user_id do
      conn
      |> put_flash(:error, "Nice try, friend. That's not a page for you.")
      |> redirect(to: Routes.item_path(conn, :index))
      |> halt()
    else
      conn
    end
  end
end

auction/apps/auction_web/lib/auction_web/views/error_view.ex
defmodule AuctionWeb.ErrorView do
  use AuctionWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

auction/apps/auction_web/lib/auction_web/views/item_view.ex
defmodule AuctionWeb.ItemView do
  use AuctionWeb, :view
end

auction/apps/auction_web/lib/auction_web/views/layout_view.ex
defmodule AuctionWeb.LayoutView do
  use AuctionWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

auction/apps/auction_web/lib/auction_web/views/page_view.ex
defmodule AuctionWeb.PageView do
  use AuctionWeb, :view
end

auction/apps/auction_web/lib/auction_web/views/session_view.ex
defmodule AuctionWeb.SessionView do
  use AuctionWeb, :view
end

auction/apps/auction_web/lib/auction_web/views/user_view.ex
defmodule AuctionWeb.UserView do
  use AuctionWeb, :view
end

auction/apps/auction_web/lib/auction_web/templates/item/edit.html.eex
<h1>Edit <%= @item.data.title %></h1>

<%= render("form.html", item: @item, action: Routes.item_path(@conn, :update, @item.data)) %>

auction/apps/auction_web/lib/auction_web/templates/item/form.html.eex
<%= form_for @item, @action, fn f -> %>
  <%= if @item.action do %>
    <div class="alert alert-danger">
      Unfortunately, there are errors in your submission. Please correct them below.
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :description %>
  <%= textarea f, :description %>
  <%= error_tag f, :description %>

  <%= label f, :ends_at, "Auction ends at" %>
  <%= datetime_select f, :ends_at %>
  <%= error_tag f, :ends_at %>

  <div>
    <%= submit "Submit" %>
  </div>
<% end %>

auction/apps/auction_web/lib/auction_web/templates/item/index.html.heex
<ul>
  <%= for item <- @items do %>
  <li>
    <%# use `mix phx.routes` to determine route's name %>
    <strong><%= link(item.title, to: Routes.item_path(@conn, :show, item)) %> </strong> - <%= item.description %>
  </li>
  <% end %>
</ul>

auction/apps/auction_web/lib/auction_web/templates/item/new.html.eex
<h1>New Item</h1>

<%= render("form.html", item: @item, action: Routes.item_path(@conn, :create)) %>

auction/apps/auction_web/lib/auction_web/templates/item/show.html.eex
<h1><%= @item.title %></h1>

<ul>
  <li><strong>Description:</strong> <%= @item.description %></li>
  <li><strong>Auction ends at:</strong> <%= format_datetime(@item.ends_at) %></li>
</ul>

<div style="display: flex; flex-direction: row;">
  <div style="flex: 1;">
    <h2>Current bids</h2>
    <%= for bid <- @item.bids do %>
      <p><%= integer_to_currency(bid.amount) %> <em>from <%= bid.user.username %></em></p>
    <% end %>
  </div>

  <div style="flex: 1;">
    <%= if @current_user do %>
      <h2>Place your bid!</h2>

      <%= form_for @bid, Routes.item_bid_path(@conn, :create, @item), fn f -> %>
        <%= if @bid.action do %>
          <div class="alert alert-danger">
            Unfortunately, there are errors in your submission. Please correct them below.
          </div>
        <% end %>

        <div class="form-group">
          <%= label f, :amount, "Bid amount", class: "control-label" %>
          <%= error_tag f, :amount %>
          <%= number_input f, :amount, class: "form-control", disabled: DateTime.compare(DateTime.utc_now(), @item.ends_at) == :gt %>
        </div>

        <%= submit "Submit", class: "btn btn-primary", disabled: DateTime.compare(DateTime.utc_now(), @item.ends_at) == :gt %>
      <% end %>
    <% end %>
  </div>
</div>

auction/apps/auction_web/lib/auction_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <div class="container" style="border-bottom: 1px solid #777777; margin-bottom: 2rem; padding-bottom: 1rem;">
    <%= link "Items", to: Routes.item_path(@conn, :index) %> |
    <%= if @current_user && @conn.private.phoenix_controller == AuctionWeb.ItemController && @conn.private.phoenix_action == :index do %>
      <%= link "New item", to: Routes.item_path(@conn, :new) %> |
    <% end %>
    <%= if @current_user && @current_user.id == if(@conn.assigns[:current_item], do: @conn.assigns.current_item.user_id, else: nil) && @conn.private.phoenix_controller == AuctionWeb.ItemController && @conn.private.phoenix_action == :show do %>
      <%= link "Edit item", to: Routes.item_path(@conn, :edit, @conn.params["id"]) %> |
    <% end %>
    <%= if @current_user do %>
      Logged in as <%= link @current_user.username, to: Routes.user_path(@conn, :show, @current_user) %> |
      <%= link "Log out", to: Routes.session_path(@conn, :delete), method: :delete %>
    <% else %>
      <%= link "login", to: Routes.session_path(@conn, :new) %>
    <% end %>
  </div>
  <%= @inner_content %>
</main>

auction/apps/auction_web/lib/auction_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

auction/apps/auction_web/lib/auction_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "AuctionWeb", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src={Routes.static_path(@conn, "/images/phoenix.png")} alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>

auction/apps/auction_web/lib/auction_web/templates/page/index.html.heex
<ul>
  <%= for item <- @items do %> 
  <li>
    <%# use `mix phx.routes` to determine route's name %>
    <strong><%= link(item.title, to: Routes.item_path(@conn, :show, item)) %> </strong> - <%= item.description %>
  </li>
  <% end %> 
</ul>

auction/apps/auction_web/lib/auction_web/templates/session/new.html.eex
<h1>Log In</h1>

<%= form_for @conn, Routes.session_path(@conn, :create), [as: :user], fn f -> %>
  <%= label f, :username %>
  <%= text_input f, :username %>
  <%= label f, :password %>
  <%= password_input f, :password %>

  <div>
    <%= submit "Submit" %>
  </div>
<% end %>

auction/apps/auction_web/lib/auction_web/templates/user/new.html.eex
<h1>User Registration</h1>
<%= form_for @user, Routes.user_path(@conn, :create), fn f -> %>
  <%= if @user.action do %>
    <div class="alert alert-danger">
      Unfortunately, there are errors in your submission. Please correct them below.
    </div>
  <% end %>

  <%= label f, :username %>
  <%= error_tag f, :username %>
  <%= text_input f, :username %>
  <%= label f, :email_address %>
  <%= error_tag f, :email_address %>
  <%= text_input f, :email_address %>
  <%= label f, :password %>
  <%= error_tag f, :password %>
  <%= password_input f, :password %>
  <%= label f, :password_confirmation %>
  <%= error_tag f, :password_confirmation %>
  <%= password_input f, :password_confirmation %>

  <div>
    <%= submit "Submit" %>
  </div>
<% end %>

auction/apps/auction_web/lib/auction_web/templates/user/show.html.eex
<h1>User details</h1>
<dl>
 <dt>Username</dt>
 <dd><%= @user.username %></dd>
 <br />
 <dt>Email address</dt>
 <dd><%= @user.email_address %></dd>
</dl>

<h2>Recent bids</h2>

<%= for bid <- @bids do %>
  <p>
    <strong><%= format_datetime(bid.inserted_at) %></strong>
    --
    <%= integer_to_currency(bid.amount) %>
    for
    <em><%= link bid.item.title, to: Routes.item_path(@conn, :show, bid.item)%></em>
  </p>
<% end %>